---

keepalive_ip : "172.28.10.30"
interface_name: "ens192"
pod_network_cidr: "192.168.0.0/16"
master1: "172.28.10.21"
master2: "172.28.10.22"
master3: "172.28.10.23"
#storage_export: "172.16.104.0/24"
